import { StyleSheet, Dimensions } from 'react-native';
import { DARK_COLORS } from './colors';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const CAMERA_WIDTH = SCREEN_WIDTH - 32;
const CAMERA_HEIGHT = SCREEN_HEIGHT * 0.48;

// Use DARK_COLORS for detection screen
const COLORS = DARK_COLORS;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 212, 255, 0.1)',
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: COLORS.cardBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.2)',
  },
  headerCenter: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 2,
  },
  sessionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  sessionId: {
    fontSize: 10,
    color: COLORS.primary,
    fontWeight: '600',
    letterSpacing: 1,
  },
  sessionIdIdle: {
    fontSize: 10,
    color: COLORS.gray,
    fontWeight: '600',
    letterSpacing: 1,
  },
  statusDotIdle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.gray,
  },
  timerContainer: {
    alignItems: 'flex-end',
    backgroundColor: COLORS.cardBg,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.2)',
  },
  timerContainerIdle: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: COLORS.cardBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  timerLabel: {
    fontSize: 8,
    color: COLORS.gray,
    letterSpacing: 1,
    marginBottom: 2,
  },
  timerValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primary,
    fontVariant: ['tabular-nums'],
    letterSpacing: 1,
  },
  cameraContainer: {
    paddingHorizontal: 16,
    marginTop: 12,
  },
  cameraFeed: {
    width: CAMERA_WIDTH,
    height: CAMERA_HEIGHT,
    backgroundColor: COLORS.darkSurface,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.3)',
  },
  cameraFeedIdle: {
    width: CAMERA_WIDTH,
    height: CAMERA_HEIGHT,
    backgroundColor: COLORS.darkSurface,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  cornerBracket: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: COLORS.primary,
    zIndex: 10,
  },
  cornerBracketIdle: {
    borderColor: COLORS.gray,
  },
  cornerTL: {
    top: 8,
    left: 8,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 4,
  },
  cornerTR: {
    top: 8,
    right: 8,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 4,
  },
  cornerBL: {
    bottom: 8,
    left: 8,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 4,
  },
  cornerBR: {
    bottom: 8,
    right: 8,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 4,
  },
  gridContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  gridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(0, 212, 255, 0.05)',
  },
  gridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(0, 212, 255, 0.05)',
  },
  gridLineIdle: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  idleCenterContent: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  idleTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 8,
  },
  idleSubtitle: {
    fontSize: 13,
    color: COLORS.gray,
  },
  crosshairOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -40,
    marginLeft: -40,
  },
  idleBottomStatus: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 30,
    padding: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  idleStatusItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  idleStatusText: {
    fontSize: 11,
    color: COLORS.gray,
    fontWeight: '500',
  },
  infoCardsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginTop: 16,
    gap: 12,
  },
  infoCard: {
    flex: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  infoCardTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.white,
    marginTop: 10,
    marginBottom: 4,
  },
  infoCardDesc: {
    fontSize: 11,
    color: COLORS.gray,
    textAlign: 'center',
  },
  startButtonContainer: {
    paddingHorizontal: 16,
    marginTop: 'auto',
    paddingBottom: 10,
    position: 'relative',
  },
  startButtonGlow: {
    position: 'absolute',
    top: 10,
    left: 30,
    right: 30,
    height: 60,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    opacity: 0.3,
  },
  startButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    overflow: 'hidden',
  },
  startButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    gap: 16,
  },
  startIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  startButtonTextContainer: {
    flex: 1,
  },
  startButtonTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 1,
  },
  startButtonSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 2,
  },
  scanLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(0, 212, 255, 0.4)',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  cameraBackground: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraPlaceholderText: {
    fontSize: 12,
    color: 'rgba(0, 212, 255, 0.4)',
    fontWeight: '600',
    letterSpacing: 3,
    marginTop: 12,
  },
  progressContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  progressBar: {
    width: 200,
    height: 4,
    backgroundColor: 'rgba(0, 212, 255, 0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 2,
  },
  progressText: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: '600',
    marginTop: 8,
  },
  hudTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  hudLeft: {
    flex: 1,
  },
  recIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.error,
  },
  recText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.error,
    letterSpacing: 1,
  },
  hudCenter: {
    flex: 1,
    alignItems: 'center',
  },
  hudRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  hudItem: {
    alignItems: 'center',
    gap: 2,
  },
  hudLabel: {
    fontSize: 8,
    color: COLORS.gray,
    letterSpacing: 1,
    marginTop: 2,
  },
  hudValue: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  hudBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  hudBottomItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  hudBottomText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  boundingBox: {
    position: 'absolute',
    width: 115,
    height: 150,
    borderWidth: 2,
    borderColor: COLORS.error,
    borderRadius: 4,
  },
  bbCorner: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderColor: COLORS.error,
  },
  bbCornerSafe: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderColor: COLORS.success,
  },
  bbCornerTL: {
    top: -2,
    left: -2,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 4,
  },
  bbCornerTR: {
    top: -2,
    right: -2,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 4,
  },
  bbCornerBL: {
    bottom: -2,
    left: -2,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 4,
  },
  bbCornerBR: {
    bottom: -2,
    right: -2,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 4,
  },
  detectionLabel: {
    position: 'absolute',
    top: -30,
    left: -2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.error,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
  },
  detectionLabelText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  crosshair: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 20,
    height: 20,
    marginTop: -10,
    marginLeft: -10,
  },
  crosshairH: {
    position: 'absolute',
    top: '50%',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 59, 92, 0.6)',
  },
  crosshairV: {
    position: 'absolute',
    left: '50%',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 59, 92, 0.6)',
  },
  boundingBoxSafe: {
    position: 'absolute',
    top: 120,
    right: 50,
    width: 95,
    height: 125,
    borderWidth: 2,
    borderColor: COLORS.success,
    borderRadius: 4,
  },
  detectionLabelSafe: {
    position: 'absolute',
    top: -30,
    left: -2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.success,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
  },
  detectionLabelTextSafe: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  aiProcessingBadge: {
    position: 'absolute',
    bottom: 50,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 255, 136, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 136, 0.3)',
  },
  aiProcessingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.success,
  },
  aiProcessingText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.success,
    letterSpacing: 1,
  },
  sessionStatsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 14,
    backgroundColor: COLORS.cardBg,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.15)',
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
  },
  statBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  statBoxLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: COLORS.gray,
    letterSpacing: 1,
  },
  statBoxValue: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  statBoxSub: {
    fontSize: 10,
    color: COLORS.gray,
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginHorizontal: 8,
  },
  detectionInfoPanel: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: COLORS.cardBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 59, 92, 0.3)',
    overflow: 'hidden',
  },
  infoPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 59, 92, 0.1)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 59, 92, 0.2)',
  },
  infoPanelDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.error,
  },
  infoPanelTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.error,
    letterSpacing: 1.5,
  },
  infoPanelContent: {
    padding: 14,
    gap: 10,
  },
  infoPanelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  infoPanelLabel: {
    fontSize: 12,
    color: COLORS.gray,
  },
  infoPanelValue: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.white,
  },
  infoPanelValueError: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.error,
  },
  buttonContainer: {
    paddingHorizontal: 16,
    marginTop: 'auto',
    paddingBottom: 10,
  },
  stopButton: {
    backgroundColor: COLORS.error,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  stopButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    gap: 12,
    zIndex: 1,
  },
  stopIconSquare: {
    width: 16,
    height: 16,
    backgroundColor: COLORS.white,
    borderRadius: 3,
  },
  stopButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 2,
  },
  stopButtonGlow: {
    position: 'absolute',
    top: -20,
    left: '50%',
    marginLeft: -75,
    width: 150,
    height: 40,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  footerStatus: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 10,
    color: COLORS.darkGray,
    letterSpacing: 1,
  },
  // Location Button Styles
  locationButton: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: COLORS.cardBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  locationButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  locationTextContainer: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 11,
    color: COLORS.gray,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  locationValue: {
    fontSize: 14,
    color: COLORS.white,
    fontWeight: '600',
  },
  locationPlaceholder: {
    color: COLORS.gray,
    fontWeight: '400',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalContainer: {
    width: '100%',
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.2)',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.white,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalContent: {
    padding: 20,
  },
  locationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.darkSurface,
    borderRadius: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.3)',
    gap: 12,
  },
  locationInput: {
    flex: 1,
    height: 50,
    fontSize: 15,
    color: COLORS.white,
  },
  modalActions: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.gray,
  },
  modalSaveButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  modalSaveText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.white,
  },
});

export { COLORS, CAMERA_WIDTH, CAMERA_HEIGHT };
